/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "JS, TS & React Native Docs",
  "tagline": "Documentation for JavaScript, TypeScript, and React Native",
  "url": "https://sammy6378.github.io",
  "baseUrl": "/reference/",
  "favicon": "img/favicon.ico",
  "organizationName": "sammy6378",
  "projectName": "reference",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "themeConfig": {
    "navbar": {
      "title": "Docs",
      "logo": {
        "alt": "Modern JavaScript Documentation",
        "src": "img/logo.svg",
        "srcDark": "img/logo-dark.svg"
      },
      "items": [
        {
          "to": "/docs/getting-started",
          "position": "left",
          "label": "Get Started"
        },
        {
          "type": "dropdown",
          "label": "Documentation",
          "position": "left",
          "items": [
            {
              "to": "/docs/Javascript/Beginner/introduction-to-javascript",
              "label": "JavaScript Basics"
            },
            {
              "to": "/docs/Javascript/Advanced",
              "label": "Advanced JavaScript"
            },
            {
              "to": "/docs/Typescript/intro",
              "label": "TypeScript"
            },
            {
              "to": "/docs/react-native/setup",
              "label": "React Native Setup"
            },
            {
              "to": "/docs/react-native/components",
              "label": "RN Components"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Resources",
          "position": "left",
          "items": [
            {
              "href": "https://github.com/sammy6378/reference/blob/main/CONTRIBUTING.md",
              "label": "Contributing"
            },
            {
              "href": "https://github.com/sammy6378/reference/discussions",
              "label": "Community"
            },
            {
              "href": "https://github.com/sammy6378/reference/issues",
              "label": "Support"
            }
          ]
        },
        {
          "href": "https://github.com/sammy6378/reference",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "/docs/getting-started"
            },
            {
              "label": "JavaScript",
              "to": "/docs/Javascript/Beginner/introduction-to-javascript"
            },
            {
              "label": "TypeScript",
              "to": "/docs/Typescript/intro"
            },
            {
              "label": "React Native",
              "to": "/docs/react-native/setup"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Advanced Topics",
              "to": "/docs/Javascript/Advanced"
            },
            {
              "label": "Contributing Guide",
              "href": "https://github.com/sammy6378/reference/blob/main/CONTRIBUTING.md"
            },
            {
              "label": "License",
              "href": "https://github.com/sammy6378/reference/blob/main/LICENSE"
            },
            {
              "label": "Changelog",
              "href": "https://github.com/sammy6378/reference/releases"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/sammy6378/reference"
            },
            {
              "label": "Discussions",
              "href": "https://github.com/sammy6378/reference/discussions"
            },
            {
              "label": "Issues & Bug Reports",
              "href": "https://github.com/sammy6378/reference/issues"
            },
            {
              "label": "Discord Community",
              "href": "https://discord.gg/sammy_in_tech"
            }
          ]
        },
        {
          "title": "Sponsor",
          "items": [
            {
              "label": "Nuvex Solutions",
              "href": "https://nuvex.com"
            },
            {
              "label": "Support the Project",
              "href": "https://github.com/sponsors/sammy6378"
            },
            {
              "label": "Contact Us",
              "href": "mailto:contact@nuvex.com"
            },
            {
              "label": "Partnership",
              "href": "mailto:partnerships@nuvex.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Modern JavaScript Documentation. Proudly sponsored by <a href=\"https://nuvex.com\" target=\"_blank\" rel=\"noopener noreferrer\">Nuvex Solutions</a>. Built with ❤️ for the developer community."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "diff",
        "json"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/sammy6378/reference/tree/main/"
        },
        "theme": {
          "customCss": "/home/runner/work/reference/reference/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "/home/runner/work/reference/reference/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "language": [
          "en"
        ],
        "highlightSearchTermsOnTargetPage": true,
        "explicitSearchResultPath": true
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
